# Generated by Django 4.0.6 on 2022-07-07 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='music',
            old_name='title2',
            new_name='title',
        ),
    ]
